---
- include_role:
    name: microk8s

- include_role:
    name: dt-activegate-classic
  vars:
    activegate_install_synthetic: true

- include_role:
    name: dt-operator

- include_role:
    name: monaco-v2
  vars:
    monaco_version: "v{{ monacoVersion }}"
    
- include_role:
    name: app-easytrade

- include_role:
    name: gitlab

- name: Gitlab - Ensure Group
  include_role:
    name: gitlab
    tasks_from: ensure-group
  vars:
    gitlab_group_name: "{{ gitlab_group }}"

- name: Gitlab - Ensure Default Group Vars
  include_role:
    name: gitlab
    tasks_from: ensure-default-group-vars
  vars:
    gitlab_group_name: "{{ gitlab_group }}"

- name: Gitlab - Ensure Project
  include_role:
    name: gitlab
    tasks_from: ensure-project
  vars:
    gitlab_prj: "{{ gitlab_repo_name }}"
    gitlab_prj_namespace_id: "{{ gitlab_group_id }}"

- name: Source Gitlab endpoint
  include_role:
    name: gitlab
    tasks_from: source-endpoints

- set_fact:
    dt_hot_gitlab_repo_src: "{{ role_path }}/files/repos/hot/logs-in-context"

- name: Publish docs
  include_role:
    name: repository
  vars:
    git_username: "root"
    git_password: "{{ gitlab_password }}"
    git_domain: "{{ gitlab_domain }}"
    git_remote: "gitlab"
    git_org: "{{ gitlab_group }}"
    git_repo: "{{ gitlab_repo_name }}"
    repo_src: "{{ dt_hot_gitlab_repo_src }}"
    track_upstream: true

# - set_fact:
#     include_dashboard_value_file: "{{ role_path }}/templates/apps-dashboard.yml.j2"

# - include_role:
#     name: dashboard
#     tasks_from: template-values-file

- include_role:
    name: dashboard
