---
- include_role:
    name: microk8s

- include_role:
    name: dt-activegate-classic
  vars:
    activegate_install_synthetic: true

- include_role:
    name: dt-operator

- include_role:
    name: monaco-v2
  vars:
    monaco_version: "v{{ monacoVersion }}"

- include_role:
    name: app-easytravel
#  vars:
#    easytravel_image_tag: "2.0.0.3599" #"latest" 


- include_role:
    name: app-hipstershop
  vars:
    hipstershop_image_tag: "latest"
    
- include_role:
    name: app-easytrade
  vars:
    easytrade_image_tag: "0d8bdc7"
    easytrade_headlessloadgen_tag: "latest"

- set_fact:
    include_dashboard_value_file: "{{ role_path }}/templates/apps-dashboard.yml.j2"

- include_role:
    name: dashboard
    tasks_from: template-values-file

- include_role:
    name: dashboard
