manifestVersion: 1.0

projects:
- name: global
  path: global

environmentGroups:
- name: acebox
  environments:
  - name: acebox
    url:
      type: environment
      value: DT_TENANT
    auth:
      token:
        type: environment
        name: DT_API_TOKEN
